### ISSUE TITLE
Manually trigger MathJax typesetting

### ISSUE THREAD

**Issue by faizplus** [davidshen84/ngx-mathjax#10]
I am trying to load mathjax like this

` <div mathjax [innerHTML]="mmlText | safeHtml: 'html'"></div>`

It renders fine for the first load but when `mmlText` values changes then it does not render.

I have tried trigger MathJax typesetting after changing the variable value but it does not work.
`
 @ViewChild(MathJaxDirective, { static: false })
  private questionStatement: MathJaxDirective;
...
changeVar(){
this.mmlText = 'new mml tags here';
 this.questionStatement.MathJaxTypeset();
}
`

**Comment by davidshen84** [comment]
@faizplus ,

Have you checked the sample code at [here][1]? This is how the library implements dynamic typesetting ATM. This is due to how MathJax v2 library handles dynamic typesetting.

In addition, this library does not expose all the functions of the MathJax library. So it does not support *mml*, it only supports *tex*.

[1]: https://github.com/davidshen84/ngx-mathjax/blob/master/src/app/demo/demo.component.ts#L34
